project:
  type: website
  output-dir: build-docs

website:
  title: "SWMM-Dash-MLFlow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Design"
        menu:
          - href: design/overview.qmd
            text: Design Overview
      - text: "Implementation"
        menu:
          - href: implement/overview.qmd
            text: Implementation Overview
      - text: "Usage"
        menu:
          - href: use/overview.qmd
            text: Usage Overview
  back-to-top-navigation: true
  reader-mode: true
  # repo-url: https://github.com/gcoyle83/python-starter-template
  issue-url: https://github.com/gcoyle83/swmm-dash-mlflow/issues
  repo-actions: [issue]
  page-footer: 
    left: "Copyright 2023, Brown and Caldwell" 
    right: 
      - icon: github
        href: https://github.com/gcoyle83/swmm-dash-mlflow
    background: light

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
